"""text

Revision ID: 49145ca44b0a
Revises: a439def60ef1
Create Date: 2026-08-12 12:22:15.496237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49145ca44b0a'
down_revision: Union[str, Sequence[str], None] = 'a439def60ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incubators', 'eggs_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incubators', 'eggs_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
