"""implementing of command db

Revision ID: 5de315d9d495
Revises: 8d0180074778
Create Date: 2026-10-04 16:14:08.636607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de315d9d495'
down_revision: Union[str, Sequence[str], None] = '8d0180074778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commands')
    # ### end Alembic commands ###
