"""text

Revision ID: 92bc51bfaac5
Revises: b683f69f803c
Create Date: 2026-08-11 21:15:46.747235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bc51bfaac5'
down_revision: Union[str, Sequence[str], None] = 'b683f69f803c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'employees', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
