"""text

Revision ID: a439def60ef1
Revises: f527f0a1d36c
Create Date: 2026-08-12 12:16:51.488136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a439def60ef1'
down_revision: Union[str, Sequence[str], None] = 'f527f0a1d36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incubators', 'state',
               existing_type=postgresql.ENUM('EMPTY', 'INCUBATING', 'BROKEN', name='incubatorstate'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incubators', 'state',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EMPTY', 'INCUBATING', 'BROKEN', name='incubatorstate'),
               existing_nullable=False)
    # ### end Alembic commands ###
