"""text

Revision ID: b1deaecd418b
Revises: c0dd7fbaa666
Create Date: 2026-08-23 22:29:40.515468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1deaecd418b'
down_revision: Union[str, Sequence[str], None] = 'c0dd7fbaa666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'title')
    # ### end Alembic commands ###
